
spring:
  cloud:
    gateway:
      routes:
        - id: seata-consumer
          uri: lb://seata-storage
          predicates:
            - Path=/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 9000
