spring:
  cloud:
    gateway:
      routes:
        - id: order_route # 路由id,要求唯一，建议配合服务名
          # uri: http://localhost:3042 # 服务的路由地址
          uri: lb://order # 匹配注册中心的服务名
          predicates:
            - Path=/order/get/** # 断言，路径匹配则路由

        - id: order_route2 # 路由id,要求唯一，建议配合服务名
          # uri: http://localhost:3042 # 服务的路由地址
          uri: lb://order # 匹配注册中心的服务名
          predicates:
            - Path=/order/list/**  # 断言，路径匹配则路由
            #- After=2022-04-05T16:35:38.522+08:00[Asia/Shanghai]
            - Cookie=username,cruise
          filters:
            - AddRequestHeader=X-Request-red, blue # 给匹配的每个请求添加这个请求头
        - id: storage_route
          uri: lb://storage-api
          predicates:
            - Path=/api/**
      discovery:
        locator:
          enabled: true # 开启从注册中心动态获取路由的功能，利用微服务名进行路由